class CfgPatches {
    class EUFOR_Backpacks {
        name = "$STR_EUFOR_Backpacks_name";
        requiredAddons[] = {
            "A3_Characters_F",
            "A3_Supplies_F_Enoch",
            "A3_Supplies_F_Exp",
            "A3_Characters_F_Orange",
        };
        author = "$STR_EUFOR_Backpacks_Author";
        authorUrl = "https://www.eudef.eu";
        version = 0.0.1;
        versionStr = "0.0.1";
        versionAr[] = {0,0,1};
        units[] = {
            "EUFOR_Backpacks_Bag_Base",
            "EUFOR_Backpacks_Tortilia_Base",
            "EUFOR_Backpacks_Tortilia_Base_Medic",
            "EUFOR_Backpacks_Tortilia_Base_Ammo",
            "EUFOR_Backpacks_Compact_Base",
            "EUFOR_Backpacks_Compact_Base_Medic",
            "EUFOR_Backpacks_Kitbag_Base",
            "EUFOR_Backpacks_Kitbag_Base_Medic",
            "EUFOR_Backpacks_Radiobag_Base",
            "EUFOR_Backpacks_Radiobag_Base_PL",
            "EUFOR_Backpacks_FieldPack_Base",
            "EUFOR_Backpacks_FieldPack_Base_Medic",
            "EUFOR_Backpacks_TacticalPack_Base",
            "EUFOR_Backpacks_TacticalPack_Base_Medic",
            "EUFOR_Backpacks_LegStrapBag_Base",
            "EUFOR_Backpacks_ViperHarness_Base",
            "EUFOR_Backpacks_ViperHarnessLight_Base",

            "EUFOR_Backpacks_Tortilia_Fleck",
            "EUFOR_Backpacks_Tortilia_Fleck_Medic",
            "EUFOR_Backpacks_Tortilia_Fleck_Ammo",
            "EUFOR_Backpacks_Compact_Fleck",
            "EUFOR_Backpacks_Compact_Fleck_Medic",
            "EUFOR_Backpacks_Kitbag_Fleck",
            "EUFOR_Backpacks_Kitbag_Fleck_Medic",
            "EUFOR_Backpacks_Radiobag_Fleck",
            "EUFOR_Backpacks_Radiobag_Fleck_PL",
            "EUFOR_Backpacks_FieldPack_Fleck",
            "EUFOR_Backpacks_FieldPack_Fleck_Medic",
            "EUFOR_Backpacks_TacticalPack_Fleck",
            "EUFOR_Backpacks_TacticalPack_Fleck_Medic",
            "EUFOR_Backpacks_LegStrapBag_Fleck",
            "EUFOR_Backpacks_ViperHarness_Fleck",
            "EUFOR_Backpacks_ViperHarnessLight_Fleck",

            "EUFOR_Backpacks_Tortilia_Multi",
            "EUFOR_Backpacks_Tortilia_Multi_Medic",
            "EUFOR_Backpacks_Tortilia_Multi_Ammo",
            "EUFOR_Backpacks_Compact_Multi",
            "EUFOR_Backpacks_Compact_Multi_Medic",
            "EUFOR_Backpacks_Kitbag_Multi",
            "EUFOR_Backpacks_Kitbag_Multi_Medic",
            "EUFOR_Backpacks_Radiobag_Multi",
            "EUFOR_Backpacks_Radiobag_Multi_PL",
            "EUFOR_Backpacks_FieldPack_Multi",
            "EUFOR_Backpacks_FieldPack_Multi_Medic",
            "EUFOR_Backpacks_TacticalPack_Multi",
            "EUFOR_Backpacks_TacticalPack_Multi_Medic",
            "EUFOR_Backpacks_LegStrapBag_Multi",
            "EUFOR_Backpacks_ViperHarness_Multi",
            "EUFOR_Backpacks_ViperHarnessLight_Multi",

            "EUFOR_Backpacks_Tortilia_Schnee",
            "EUFOR_Backpacks_Tortilia_Schnee_Medic",
            "EUFOR_Backpacks_Tortilia_Schnee_Ammo",
            "EUFOR_Backpacks_Compact_Schnee",
            "EUFOR_Backpacks_Compact_Schnee_Medic",
            "EUFOR_Backpacks_Kitbag_Schnee",
            "EUFOR_Backpacks_Kitbag_Schnee_Medic",
            "EUFOR_Backpacks_Radiobag_Schnee",
            "EUFOR_Backpacks_Radiobag_Schnee_PL",
            "EUFOR_Backpacks_FieldPack_Schnee",
            "EUFOR_Backpacks_FieldPack_Schnee_Medic",
            "EUFOR_Backpacks_TacticalPack_Schnee",
            "EUFOR_Backpacks_TacticalPack_Schnee_Medic",
            "EUFOR_Backpacks_LegStrapBag_Schnee",
            "EUFOR_Backpacks_ViperHarness_Schnee",
            "EUFOR_Backpacks_ViperHarnessLight_Schnee",

            "EUFOR_Backpacks_Tortilia_Tropen",
            "EUFOR_Backpacks_Tortilia_Tropen_Medic",
            "EUFOR_Backpacks_Tortilia_Tropen_Ammo",
            "EUFOR_Backpacks_Compact_Tropen",
            "EUFOR_Backpacks_Compact_Tropen_Medic",
            "EUFOR_Backpacks_Kitbag_Tropen",
            "EUFOR_Backpacks_Kitbag_Tropen_Medic",
            "EUFOR_Backpacks_Radiobag_Tropen",
            "EUFOR_Backpacks_Radiobag_Tropen_PL",
            "EUFOR_Backpacks_FieldPack_Tropen",
            "EUFOR_Backpacks_FieldPack_Tropen_Medic",
            "EUFOR_Backpacks_TacticalPack_Tropen",
            "EUFOR_Backpacks_TacticalPack_Tropen_Medic",
            "EUFOR_Backpacks_LegStrapBag_Tropen",
            "EUFOR_Backpacks_ViperHarness_Tropen",
            "EUFOR_Backpacks_ViperHarnessLight_Tropen",

            "EUFOR_Backpacks_Tortilia_TropenD",
            "EUFOR_Backpacks_Tortilia_TropenD_Medic",
            "EUFOR_Backpacks_Tortilia_TropenD_Ammo",
            "EUFOR_Backpacks_Compact_TropenD",
            "EUFOR_Backpacks_Compact_TropenD_Medic",
            "EUFOR_Backpacks_Kitbag_TropenD",
            "EUFOR_Backpacks_Kitbag_TropenD_Medic",
            "EUFOR_Backpacks_Radiobag_TropenD",
            "EUFOR_Backpacks_Radiobag_TropenD_PL",
            "EUFOR_Backpacks_FieldPack_TropenD",
            "EUFOR_Backpacks_FieldPack_TropenD_Medic",
            "EUFOR_Backpacks_TacticalPack_TropenD",
            "EUFOR_Backpacks_TacticalPack_TropenD_Medic",
            "EUFOR_Backpacks_LegStrapBag_TropenD",
            "EUFOR_Backpacks_ViperHarness_TropenD",
            "EUFOR_Backpacks_ViperHarnessLight_TropenD",

            "EUFOR_Backpacks_Tortilia_Medic",
            "EUFOR_Backpacks_Tortilia_Medic_1",
            "EUFOR_Backpacks_Tortilia_Medic_2",
            "EUFOR_Backpacks_Compact_Medic",
            "EUFOR_Backpacks_Compact_Medic_1",
            "EUFOR_Backpacks_Compact_Medic_2",
            "EUFOR_Backpacks_Compact_Medic_3",
            "EUFOR_Backpacks_Kitbag_Medic",
            "EUFOR_Backpacks_Kitbag_Medic_1",
            "EUFOR_Backpacks_Kitbag_Medic_2",
            "EUFOR_Backpacks_Kitbag_Medic_3"
        };
        weapons[] = {};
        magazines[] = { };
    };
};
